### ISSUE TITLE
Simple status for cdx-sync-client

### ISSUE THREAD

**Issue by nditada** [instedd/cdx-sync-client#16]
Clicking on the tray icon should display a mini screen with a simple status:
- connected/disconnected
- "All results sent"
- "Reporting results..."
- "Error: " + [link to log file]

**Comment by waj** [comment]
This was implemented a little bit different from the original specification: the icon still shows a popup menu when clicked and the notifications are displayed using a bubble message. The icon is animated during the synchronization and it turns red when the last synchronization has failed.
