### ISSUE TITLE
Avoid Windows Firewall asking to block rsync connections

### ISSUE THREAD

**Issue by matiasgarciaisaia** [instedd/cdx-sync-client#22]
On the first run after installation, Windows Firewall asks the user to allow or block `rsync` connections:

![](https://cloud.githubusercontent.com/assets/5470539/9175187/a77d1216-3f5a-11e5-948d-c166c24292a8.png)

We should add the exception automatically from the installer, or, if we can't, rename the executable to something like `cdx-rsync` so the user knows it's something to allow.

**Comment by mmuller** [comment]
Now Windows Firewall doesn't ask the user to allow or block rsync connections.
