### ISSUE TITLE
CDxSettings still pointing to old stg URL

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx-sync-client#30]
When trying to sync a device created in https://cdx-stg.instedd.org the client fails registering it with the following error:
`Service Temporarily Unavailable. Try again?`

_authServerUrl_ in CDXSettings.java file is pointing to  **cdp-stg.instedd.org** and should be pointing to new URL.

**Comment by mmuller** [comment]
Ok in version 0.7-pre10
